print('==== DESAFIO 4 ====')
n=input('Digite algo: ')
print('O tipo primitivo da variável é', type(n))
print('Só tem espaços ?', n.isspace())
print(f'É um número? {n.isnumeric()}')
print('É alfabetico? ', n.isalpha())
print('É alfanumérico? ', n.isalnum())
print('É todo maiúsculo? ', n.isupper())
print(f'É minúsculo? {n.islower()}')
print('Está capitalizada? ', n.istitle())