d=(' DESAFIO 12 ')
print('{:=^31}'.format(d))
print('='*31)
print('CALCULANDO DESCONTOS')
print('='*31)
p=float(input('Informe o preço do produto: R$ '))
d=float(input('Quantos % de desconto você recebeu? '))
des=p-(p*d/100)
print('O item de R$ {:.2f}, custará R$ {:.2f}'.format(p, des))
print('='*31)