d=(' Desafio 22 ')
print('{:=^31}'.format(d))
print('='*31)
nome=str(input('Informe seu nome completo: '))
print('Analisando seu nome ->')
print('Seu nome em maiúsculas é {}.'.format(nome.upper()))
print('Seu nome em minúsculas é {}.'.format(nome.lower()))
print('Ao todo, seu nome tem {} letras.'.format(len(nome) - nome.count(' ')))
n=nome.split()
print('Seu primeiro nome é {} e ele tem {} letras.'.format(n[0], len(n[0])))